# Generated by Django 3.2.4 on 2023-11-28 07:52

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='blog/cover', validators=[blog.validators.validate_file_size]),
        ),
    ]
